//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakeem
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.nuskha_comment = new HashSet<nuskha_comment>();
            this.favourite_hakeem = new HashSet<favourite_hakeem>();
            this.favourite_nuskha = new HashSet<favourite_nuskha>();
            this.nuskhas = new HashSet<nuskha>();
        }
    
        public int account_id { get; set; }
        public string account_name { get; set; }
        public string account_email { get; set; }
        public string account_passeord { get; set; }
        public string account_type { get; set; }
        public Nullable<System.DateTime> account_insertion { get; set; }
        public string axxount_gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nuskha_comment> nuskha_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_hakeem> favourite_hakeem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_nuskha> favourite_nuskha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nuskha> nuskhas { get; set; }
    }
}
