//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakeem
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite_hakeem
    {
        public int favourite_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> hakeem_id { get; set; }
        public Nullable<int> stars { get; set; }
    
        public virtual account account { get; set; }
    }
}
