//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakeem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hakeemEntities : DbContext
    {
        public hakeemEntities()
            : base("name=hakeemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<disease> diseases { get; set; }
        public virtual DbSet<favourite_hakeem> favourite_hakeem { get; set; }
        public virtual DbSet<favourite_nuskha> favourite_nuskha { get; set; }
        public virtual DbSet<nuskha> nuskhas { get; set; }
        public virtual DbSet<nuskha_comment> nuskha_comment { get; set; }
        public virtual DbSet<symptom> symptoms { get; set; }
    }
}
