//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakeem
{
    using System;
    using System.Collections.Generic;
    
    public partial class nuskha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nuskha()
        {
            this.favourite_nuskha = new HashSet<favourite_nuskha>();
            this.nuskha_comment = new HashSet<nuskha_comment>();
        }
    
        public int nuskha_id { get; set; }
        public string nuskha_name { get; set; }
        public string nuskha_description { get; set; }
        public byte[] nuskha_image { get; set; }
        public string nuskha_imgtype { get; set; }
        public string nuskha_ingredients { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> disease_id { get; set; }
        public Nullable<int> symptoms_id { get; set; }
        public string symptoms { get; set; }
    
        public virtual account account { get; set; }
        public virtual disease disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_nuskha> favourite_nuskha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nuskha_comment> nuskha_comment { get; set; }
        public virtual symptom symptom { get; set; }
    }
}
